package com.b4code.backend.models;

public enum RoomType {
    STANDARD_ROOM,
    DELUXE_ROOM,
    SUPERIOR_ROOM,
    EXECUTIVE_ROOM,
    TWIN_ROOM,
    FAMILY_ROOM,
    STUDIO_ROOM,
    SUITE,
    PRESIDENTIAL_SUITE,
    VILLA,
    PREMIER_ROOM,
    EXECUTIVE_SUITE,
    LUXURY_ROOM,
    GARDEN_VIEW_ROOM,
    OCEAN_VIEW_ROOM,
    POOL_VILLA,
    BEDROOM_SUITE,
    GARDEN_SUITE,
    CHAMBER,
    MASTER_SUITE,
    PREMIUM_ROOM,
    PREMIER_OCEAN_VIEW,
    LAGOON_VIEW_ROOM
}
